project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: CV.qmd
        text: CV
      - href: contact.qmd
        text: Contact
  page-footer:
    right: "Â© 2025 Rebecca Li"

format:
  html:
    theme: cosmo
    toc: false
